version: '3.7'

services:
  api:
    container_name: subscriptions-state-machine
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
  redis:
    image : redis:6
    container_name: subscriptions-state-machine-redis
    command:
      - "redis-server"
      - "--requirepass ${REDIS_PASSWORD}"
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  postgres:
    container_name: subscriptions-state-machine-postgres
    image: postgres:16
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  app-network:
volumes:
  pgdata: {}
