export enum UserSubscriptionStatesEnum {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  ACTIVE_MANUAL = 'ACTIVE_MANUAL',
  ACTIVE_MOBILE = 'ACTIVE_MOBILE',
  PENDING = 'PENDING',
  CANCELLED_ACTIVE = 'CANCELLED_ACTIVE',
  CANCELLED_ACTIVE_MOBILE = 'CANCELLED_ACTIVE_MOBILE',
  FREEMIUM_BEFORE_TRIAL = 'FREEMIUM_BEFORE_TRIAL',
  FREEMIUM_AFTER_TRIAL = 'FREEMIUM_AFTER_TRIAL',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_FAILED_IN_GRACE = 'PAYMENT_FAILED_IN_GRACE',
}
