export enum SubscriptionStatusEnum {
  ACTIVE = 'ACTIVE',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  ON_HOLD = 'ON_HOLD',
  PAUSED = 'PAUSED',
  IN_GRACE = 'IN_GRACE',
  PENDING = 'PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}
