export enum StripeWebhookEventTypesEnum {
  CHARGE_FAILED = 'charge.failed',
  CHARGE_SUCCEEDED = 'charge.succeeded',
  CUSTOMER_DELETED = 'customer.deleted',
  INVOICE_CREATED = 'invoice.created',
  INVOICE_PAYMENT_FAILED = 'invoice.payment_failed',
  INVOICE_UPDATED = 'invoice.updated',
  PAYMENT_INTENT_CANCELED = 'payment_intent.canceled',
  PAYMENT_INTENT_CREATED = 'payment_intent.created',
  PAYMENT_INTENT_PAYMENT_FAILED = 'payment_intent.payment_failed',
  PAYMENT_INTENT_REQUIRES_ACTION = 'payment_intent.requires_action',
  PAYMENT_INTENT_SUCCEEDED = 'payment_intent.succeeded',
  PAYMENT_METHOD_ATTACHED = 'payment_method.attached',
  SUBSCRIPTION_DELETED = 'customer.subscription.deleted',
  SUBSCRIPTION_PENDING_UPDATE_APPLIED = 'customer.subscription.pending_update_applied',
  SUBSCRIPTION_PENDING_UPDATE_EXPIRED = 'customer.subscription.pending_update_expired',
  SUBSCRIPTION_UPDATED = 'customer.subscription.updated',
}
